### ISSUE TITLE
Create instructions on how to deploy and access the protocol-reporting tool

### ISSUE THREAD

**Issue by mac-arrap** [kiva/protocol-reporting#17]
Scenario
* A protocol-reporting user is able to query the reporting service associated with a core protocol environment and see exactly how many test EKYC checks they have made

Plan

* create a document that shows how to deploy a protocol-reporting instance and also connect to an existing protocol environment
* a document showing how to make certain queries into the protocol reporting service and get meaning from them

**Comment by matt-raffel-kiva** [comment]
this is done, best I can tell
