### ISSUE TITLE
Add reporting service to Kiva STAGING

### ISSUE THREAD

**Issue by mac-arrap** [kiva/protocol-reporting#18]
We need to add a new pod to the staging network that contains the postgres database that is meant for the reporting service. This might be done in the terraform files or using the docker compose. This must be figured out in order to complete the task.  

[dock-compose](https://github.com/kiva/protocol-implementation-honduras/blob/main/controllers/docker-compose.yml)
[Helm  file](https://github.com/kiva/protocol-reporting/blob/main/helm-config/values.yaml)

**Comment by matt-raffel-kiva** [comment]
closing due to project shutdown
